name: Build Kivy APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-setuptools git unzip openjdk-17-jdk wget

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.36

      - name: Setup Android SDK & NDK
        run: |
          export ANDROIDSDK=$HOME/android-sdk
          mkdir -p $ANDROIDSDK/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-9477386_latest.zip -d $ANDROIDSDK/cmdline-tools
          mv $ANDROIDSDK/cmdline-tools/cmdline-tools $ANDROIDSDK/cmdline-tools/latest

          yes | $ANDROIDSDK/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROIDSDK --licenses
          $ANDROIDSDK/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROIDSDK \
            "build-tools;36.1.0" \
            "platforms;android-33" \
            "platform-tools"
            
      - name: Force Android NDK r25b
        run: |
          export ANDROIDSDK=$HOME/android-sdk
          $ANDROIDSDK/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROIDSDK "ndk;25.2.9519653"

          echo "ANDROID_NDK_HOME=$ANDROIDSDK/ndk/25.2.9519653" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$ANDROIDSDK/ndk/25.2.9519653" >> $GITHUB_ENV
          echo "ANDROID_NDK=$ANDROIDSDK/ndk/25.2.9519653" >> $GITHUB_ENV

      - name: Build APK
        run: |
          export ANDROIDSDK=$HOME/android-sdk
          export PATH=$ANDROIDSDK/platform-tools:$PATH
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: APK-output
          path: bin/*.apk
