name: Build Kivy APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-setuptools git unzip openjdk-17-jdk wget

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.36

      - name: Setup Android SDK & NDK
        run: |
          export ANDROIDSDK=$HOME/android-sdk
          mkdir -p $ANDROIDSDK/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip -q commandlinetools-linux-9477386_latest.zip -d $ANDROIDSDK/cmdline-tools
          mv $ANDROIDSDK/cmdline-tools/cmdline-tools $ANDROIDSDK/cmdline-tools/latest

          # قبول تمام لایسنس‌ها
          yes | $ANDROIDSDK/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROIDSDK --licenses

          # نصب Build-Tools 36.1، Android 33 و Platform-Tools
          $ANDROIDSDK/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROIDSDK "build-tools;36.1.0" "platforms;android-33" "platform-tools"

      - name: Build APK
        run: |
          export ANDROIDSDK=$HOME/android-sdk
          export PATH=$ANDROIDSDK/platform-tools:$PATH
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: APK-output
          path: bin/*.apk
