name: Build Kivy APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROIDSDK: ${{ github.workspace }}/android-sdk
      ANDROIDNDK: ${{ github.workspace }}/android-sdk/ndk/25.1.8937393
      ANDROIDAPI: 33
      BUILD_TOOLS: 33.0.2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3 python3-pip python3-setuptools git unzip wget openjdk-17-jdk

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.36

      - name: Clean previous Buildozer platforms
        run: rm -rf .buildozer/android/platform

      - name: Install Android SDK, Build Tools, and NDK
        run: |
          mkdir -p $ANDROIDSDK/cmdline-tools
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip commandlinetools-linux-9477386_latest.zip -d $ANDROIDSDK/cmdline-tools
          yes | $ANDROIDSDK/cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$ANDROIDSDK "platform-tools" "platforms;android-${ANDROIDAPI}" "build-tools;${BUILD_TOOLS}" "ndk;25.1.8937393"

      - name: Check buildozer.spec
        run: cat buildozer.spec

      - name: Build APK
        run: |
          export ANDROIDSDK=$ANDROIDSDK
          export ANDROIDNDK=$ANDROIDNDK
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: APK-output
          path: bin/*.apk
